## Arrays with python Lists

In [2]:
v = [0.5 , .75,1.0,1.5,2.0]
type(v)

list

In [3]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [4]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [5]:
m[1][0]

0.5

In [6]:
v1 = [0.5,1.5]
v2 = [1,2]
m = [v1,v2]
c = [m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [7]:
c[1][1][0]

1

In [8]:
# reference pointers to the original objects
v = [0.5,0.75,1.0,1.5,2.0]
m =[v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [9]:
v[0]= 'Python'

In [10]:
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [11]:
# avoinding this can be done with deepcopy
from copy import deepcopy

In [12]:
v = [0.5 , 0.75 , 1.0,1.5,2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [13]:
v[0]= 'python'

In [14]:
#instead of reference pointer phyial copies are used 
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## The Python array Class

In [15]:
v = [0.5 , 0.75,1.0,1.5,2.0]

In [16]:
import array

In [17]:
a = array.array('f',v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [18]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [19]:
a.extend([5.0,6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [20]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [21]:
a.append('string')

TypeError: must be real number, not str

In [ ]:
a.tolist

In [ ]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [ ]:
with open('array.apy', 'wb') as f:
    a.tofile(f)

In [ ]:
b = array.array('f')

In [ ]:
with open('array.apy', 'rb') as f:
    b.fromfile(f , 5)

In [ ]:
b

## Regular NumPy Arrays

In [1]:
import numpy as np


In [23]:
a = np.array([0 , 0.5 , 1.0,1.5,2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
type(a)

numpy.ndarray

In [ ]:
a = np.array(['a','b','c'])
a

In [ ]:
a = np.arange(2,20,2)
a

In [ ]:
a = np.arange(8 , dtype = np.float)
a

In [ ]:
a[5:]

In [ ]:
a[:2]

In [ ]:
a.sum()

In [ ]:
a.std()

In [ ]:
a.cumsum()

In [ ]:
2*a

In [ ]:
a**2

In [ ]:
a** a

In [ ]:
np.exp(a)

In [ ]:
np.sqrt(a)

## Multiple dimensions

In [26]:
b = np.array([a , a *2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [27]:
b[0]

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
b[0,2]

1.0

In [30]:
b[:,1]

array([0.5, 1. ])

In [31]:
b.sum()

15.0

In [32]:
b.sum(axis = 0)

array([0. , 1.5, 3. , 4.5, 6. ])

In [33]:
b.sum(axis = 1)

array([ 5., 10.])

In [2]:
g = np.linspace(5, 15, 12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

# Metainformation 


In [4]:
g.size


12

In [5]:
g.itemsize

8

In [6]:
g.ndim

1

In [7]:
g.shape

(12,)

In [8]:
g.dtype

dtype('float64')

In [9]:
g.nbytes

96

## Reshaping and Resizing 

In [3]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
g.shape

(15,)

In [5]:
np.shape(g)

(15,)

In [6]:
 g.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
h = g.reshape((5,3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [9]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [10]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.resize(g , (3 , 1))

array([[0],
       [1],
       [2]])

In [12]:
np.resize(g , (1,5))

array([[0, 1, 2, 3, 4]])

In [13]:
n = np.resize(g , (5,4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [14]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
np.hstack((h , 2*h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [17]:
np.vstack((h , 0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [18]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
h.flatten(order = "c")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
h.flatten( order = 'f')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [22]:
for i in h.flat:
    print(i , end = ' , ')

0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10 , 11 , 12 , 13 , 14 , 

In [25]:
for i in h.ravel(order = 'C'):
    print( i , end = ',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

## Boolean Arrays 

In [26]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
h > 8 

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [29]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [30]:
(h==5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
(h >4) & (h<=12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [32]:
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [33]:
h[(h > 4 ) & (h <= 12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
h[(h < 4 ) | (h >= 12)]

array([ 0,  1,  2,  3, 12, 13, 14])

In [35]:
np.where(h > 7 , 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
np.where(h % 2 == 0, 'true', 'false')

array([['true', 'false', 'true'],
       ['false', 'true', 'false'],
       ['true', 'false', 'true'],
       ['false', 'true', 'false'],
       ['true', 'false', 'true']], dtype='<U5')

## Speed Comparison 

In [39]:
import random 
I = 5000

In [43]:
%time mat = [[ random.gauss(0,1) for j in range(I)] for i in range(I)]


Wall time: 37.7 s


In [46]:
%time mat = np.random.standard_normal((I,I))

Wall time: 1.45 s


## Structured NumPy Arrays 

In [48]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [49]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [50]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],'formats':'O int float int,int'.split()})

In [51]:
dt

dtype([('Name', 'O'), ('Age', '<i4'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i4'), ('f1', '<i4')])])

In [53]:
s = np.array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i4'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i4'), ('f1', '<i4')])])

In [54]:
type(s)

numpy.ndarray

In [56]:
s['Name']

array(['Smith', 'Jones'], dtype=object)

In [57]:
s['Height']

array([1.83, 1.72])

In [59]:
s[0]

('Smith', 45, 1.83, (0, 1))

In [60]:
s[1]['Age']

53

## Vectoriztion of Code

In [61]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [62]:
r,s

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([[0. , 0.5, 1. ],
        [1.5, 2. , 2.5],
        [3. , 3.5, 4. ],
        [4.5, 5. , 5.5]]))

In [63]:
r+s


array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [64]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [67]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [68]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
r.shape

(4, 3)

In [71]:
s = np.arange(0,12,4)
s

array([0, 4, 8])

In [72]:
r +s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [74]:
s = np.arange(0, 12, 3)
s

array([0, 3, 6, 9])

In [75]:
r +s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [76]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [77]:
sr = s.reshape(-1, 1)
sr

array([[0],
       [3],
       [6],
       [9]])

In [78]:
sr.shape

(4, 1)

In [79]:
r + s.reshape(-1, 1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

## Memory Layout

In [92]:
x = np.random.standard_normal((1000000, 5))

In [94]:
y = 2 * x + 3

In [89]:
C = np.array((x, y), order='C')

In [95]:
F = np.array((x, y), order='F')

In [96]:
x = 0.0; y = 0.0

In [97]:
C[:2].round(2)

array([0., 0.])